#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later OR Proprietary
#
# Shared `nyia config` command UX (Plan 282).
# Sourced by BOTH the dev dispatcher (bin/nyia) and the runtime dispatcher
# (generated by scripts/preprocess-runtime.sh) so the config command behavior
# never drifts between editions. The resolver/validator/writer engine lives in
# command-policy.sh (already shared); this file holds the dispatcher-level UX:
# view, write (project|global), get, and help.
#
# Entry point: nyia_config_command "$@"  — handles everything EXCEPT list/dump,
# which remain dispatcher-local. Callers route list/dump first, then delegate.

# Load guard (idempotent under double-source).
if [[ -n "${_NYIA_CONFIG_COMMANDS_LOADED:-}" ]]; then
    return 0 2>/dev/null || true
fi
_NYIA_CONFIG_COMMANDS_LOADED=1

# Source the policy engine RELATIVE TO THIS FILE so it resolves correctly in both
# the dist tree (dist/runtime/lib/) and the installed layout
# (~/.local/lib/nyiakeeper/) — both keep the libs together. command-policy.sh has
# its own load guard, so double-sourcing is safe.
_cc_lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1090
source "$_cc_lib_dir/command-policy.sh"

_config_show_help() {
    echo "Usage: nyia config <command> [options]"
    echo ""
    echo "Read Configuration:"
    echo "  view [assistant]              Show effective values with sources"
    echo "  list [--show-origin]          Show infrastructure configuration"
    echo "  dump                          Show all configuration with environment"
    echo "  get <key>                     Get an infrastructure path (home, config, data)"
    echo ""
    echo "Write Configuration:"
    echo "  project [assistant] key=value Set project-level config"
    echo "  global [assistant] key=value  Set global-level config"
    echo ""
    echo "User-Manageable Keys:"
    echo "  command_mode     Command approval mode (safe or full)"
    echo "  rag_model        Embedding model for RAG search"
    echo "  team_dir         Path to team shared directory (skills, agents, prompts)"
    echo "  workspace_sync   Auto-sync branches in workspace mode (true or false)"
    echo "  auto_branch      Auto-create a timestamped work branch (true or false)"
    echo ""
    echo "Examples:"
    echo "  nyia config view                          # All effective values"
    echo "  nyia config view claude                   # Claude-specific values"
    echo "  nyia config project claude command_mode=full"
    echo "  nyia config global command_mode=safe"
    echo "  nyia config project rag_model=mxbai-embed-large"
    echo ""
    echo "Flags:"
    echo "  --yes    Skip confirmation for dangerous changes (non-interactive)"
}

# Handle write: nyia config project|global [assistant] key=value [--yes]
_config_handle_write() {
    local scope="$1"
    shift

    if [[ $# -eq 0 ]]; then
        echo "Error: Missing key=value argument" >&2
        echo "Usage: nyia config $scope [assistant] key=value" >&2
        exit 1
    fi

    # Parse: optional assistant name, then key=value, then optional --yes
    local assistant=""
    local key_value=""
    local yes_flag="false"
    local arg

    for arg in "$@"; do
        if [[ "$arg" == "--yes" ]]; then
            yes_flag="true"
        elif [[ "$arg" == *=* ]]; then
            key_value="$arg"
        else
            # Not a key=value and not --yes — treat as assistant name
            if [[ -z "$assistant" ]]; then
                assistant="$arg"
            else
                echo "Error: Unexpected argument: $arg" >&2
                echo "Usage: nyia config $scope [assistant] key=value [--yes]" >&2
                exit 1
            fi
        fi
    done

    if [[ -z "$key_value" ]]; then
        echo "Error: Missing key=value argument" >&2
        echo "Usage: nyia config $scope [assistant] key=value [--yes]" >&2
        exit 1
    fi

    local short_key="${key_value%%=*}"
    local value="${key_value#*=}"

    # Map short key to internal name
    local internal_key
    internal_key=$(_map_config_key_name "$short_key")
    if [[ -z "$internal_key" ]]; then
        echo "Error: Unknown config key: $short_key" >&2
        echo "" >&2
        echo "User-manageable keys:" >&2
        echo "  command_mode     Command approval mode (safe or full)" >&2
        echo "  rag_model        Embedding model for RAG search" >&2
        exit 1
    fi

    # Validate value
    if ! validate_config_value "$short_key" "$value"; then
        exit 1
    fi

    # Dangerous value confirmation gate
    if [[ "$internal_key" == "NYIA_COMMAND_MODE" && "$value" == "full" && "$scope" == "global" ]]; then
        if [[ "$yes_flag" != "true" ]]; then
            # Check if we have a TTY
            if [[ ! -t 0 ]]; then
                echo "Error: Dangerous config change requires confirmation." >&2
                echo "Use --yes to skip in non-interactive mode." >&2
                echo "" >&2
                echo "  nyia config global command_mode=full --yes" >&2
                exit 1
            fi
            echo "WARNING: Setting command_mode=full globally disables all command approval prompts."
            echo "This affects ALL assistants and ALL projects."
            read -p "Continue? [y/N]: " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                echo "Cancelled."
                exit 0
            fi
        fi
    fi

    # Determine project path for project scope
    local project_path=""
    if [[ "$scope" == "project" ]]; then
        project_path="$(pwd)"
        if [[ ! -d "$project_path/.nyiakeeper" ]]; then
            echo "Error: No .nyiakeeper directory found in current directory" >&2
            echo "Are you in a Nyia Keeper project?" >&2
            exit 1
        fi
    fi

    # Get target file and write
    local target_file
    target_file=$(get_config_target_file "$scope" "$assistant" "$project_path") || exit 1
    write_config_value "$target_file" "$internal_key" "$value"

    # Confirmation output
    local scope_label="$scope"
    if [[ -n "$assistant" ]]; then
        scope_label="${scope}+${assistant}"
    fi
    echo "Set $short_key=$value (scope: $scope_label)"
    echo "  File: $target_file"
}

# Handle view: nyia config view [assistant]
_config_handle_view() {
    local assistant="${1:-}"
    local project_path=""

    # Detect project path if in a project directory
    if [[ -d "$(pwd)/.nyiakeeper" ]]; then
        project_path="$(pwd)"
    fi

    echo "Nyia Keeper Effective Configuration:"
    echo ""

    if [[ -n "$assistant" ]]; then
        echo "Assistant: $assistant"
    else
        echo "Scope: cross-assistant"
    fi
    echo ""

    local key
    for key in "${NYIA_USER_CONFIG_KEYS[@]}"; do
        local short_name
        case "$key" in
            NYIA_COMMAND_MODE) short_name="command_mode" ;;
            NYIA_RAG_MODEL) short_name="rag_model" ;;
            NYIA_TEAM_DIR) short_name="team_dir" ;;
            NYIA_MARKETPLACE_URL) short_name="marketplace_url" ;;
            NYIA_WORKSPACE_SYNC) short_name="workspace_sync" ;;
            NYIA_WHATSUP_ENABLED) short_name="whatsup_enabled" ;;
            NYIA_WHATSUP_AUTO_READ) short_name="whatsup_auto_read" ;;
            NYIA_AUTO_BRANCH) short_name="auto_branch" ;;
            NYIA_GIT_HISTORY_CUTOFF) short_name="git_history_cutoff" ;;
            NYIA_NETWORK_EGRESS_POLICY) short_name="network_egress_policy" ;;
            NYIA_AUTH_PROFILE) short_name="auth_profile" ;;
            *) short_name="$key" ;;
        esac

        local effective
        effective=$(read_effective_config_value "$key" "$assistant" "$project_path")
        echo "  $short_name = $effective"
    done

    echo ""
    echo "Precedence: CLI > project+assistant > project-private > project > project-shared > global+assistant > global > team > default"
}

# Handle get: nyia config get <key> — infrastructure paths only (home/config/data).
_config_handle_get() {
    local key="${1:-}"
    if [[ -z "$key" ]]; then
        echo "Error: nyia config get requires a key" >&2
        return 1
    fi
    case "$key" in
        NYIAKEEPER_HOME|home) echo "${NYIAKEEPER_HOME:-}" ;;
        CONFIG_DIR|config) echo "${CONFIG_DIR:-}" ;;
        DATA_DIR|data) echo "${NYIAKEEPER_HOME:-}/data" ;;
        *)
            echo "Unknown config key: $key" >&2
            echo "(config get returns infrastructure paths only: home, config, data;" >&2
            echo " use 'nyia config view' for registered config keys)" >&2
            return 1
            ;;
    esac
}

# Shared dispatch entry — handles everything EXCEPT list/dump (dispatcher-local).
nyia_config_command() {
    if [[ $# -eq 0 ]]; then
        _config_show_help
        return 0
    fi
    local subcommand="$1"
    shift
    case "$subcommand" in
        project|global)
            _config_handle_write "$subcommand" "$@"
            ;;
        view)
            _config_handle_view "$@"
            ;;
        get)
            _config_handle_get "$@"
            ;;
        help|--help|-h)
            _config_show_help
            ;;
        *)
            echo "Error: Unknown config command: $subcommand" >&2
            echo "" >&2
            _config_show_help >&2
            exit 1
            ;;
    esac
}
