#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later OR Proprietary
#
# `nyia profile` command UX (Plan 286 — authentication profiles).
# Sourced by BOTH the dev dispatcher (bin/nyia) and the runtime dispatcher
# (generated by scripts/preprocess-runtime.sh) so behavior never drifts.
#
# A "profile" namespaces per-assistant authentication so one user can hold
# multiple accounts (e.g. two Claude logins). V1 is read-only enumeration:
# profiles are created implicitly the first time you `--profile <name> --login`.
# The resolver (resolve_active_profile / resolve_assistant_auth_dir) lives in
# bin/common-functions.sh; this file only adds the `list` UX.

# Load guard (idempotent under double-source).
if [[ -n "${_NYIA_PROFILE_COMMANDS_LOADED:-}" ]]; then
    return 0 2>/dev/null || true
fi
_NYIA_PROFILE_COMMANDS_LOADED=1

_profile_show_help() {
    echo "Usage: nyia profile <command>"
    echo ""
    echo "Commands:"
    echo "  list                       List profiles (active marker + mode)"
    echo "  create <name>              Register an auth-only profile (inherits global)"
    echo "  create <name> --persona [--from tech|non-tech|empty]"
    echo "                             Create an isolated persona with its OWN content"
    echo ""
    echo "About profiles:"
    echo "  A profile isolates per-assistant AUTHENTICATION so you can keep multiple"
    echo "  accounts (e.g. two Claude logins). The 'default' profile is the legacy"
    echo "  behavior (global dirs) and always exists."
    echo ""
    echo "  By default a named profile is AUTH-ONLY: it uses its own account but"
    echo "  INHERITS your global skills, agents, and prompt-override rules, so"
    echo "  switching accounts keeps your setup. Nyia's base prompt, base skills,"
    echo "  and team/project content are always present in every profile."
    echo ""
    echo "  # Two accounts, same setup (auth-only — no content to manage):"
    echo "    nyia-claude --profile work --login"
    echo "    nyia-claude --profile work"
    echo ""
    echo "  # A separate persona with its OWN skills/agents/rules:"
    echo "    nyia profile create accounting --persona --from non-tech"
    echo "    nyia-claude --profile accounting --login"
    echo "    nyia-claude --profile accounting"
    echo ""
    echo "  Select the active profile per-command with --profile <name>, or set a"
    echo "  default globally:"
    echo ""
    echo "    nyia config global auth_profile=accounting"
    echo ""
    echo "  Note: nyia config settings stay global across profiles. Shell-exported"
    echo "  API keys (export OPENAI_API_KEY=...) are global by nature and are NOT"
    echo "  profiled. Team and project content applies to every profile."
}

# Content markers for `profile list`: which kinds of user content a named profile
# actually carries. Truthful counting — scaffolding alone does not light a marker:
# skills need a */SKILL.md, agents need a *.md file, prompts need an activated
# (non-.example) *-overrides.md.
_profile_content_markers() {
    local nyia_home="$1" name="$2"
    local markers=""
    local d
    d="$nyia_home/profiles/$name/skills"
    if compgen -G "$d/*/SKILL.md" >/dev/null 2>&1; then
        markers+="${markers:+ }skills"
    fi
    d="$nyia_home/profiles/$name/agents"
    if compgen -G "$d/*.md" >/dev/null 2>&1; then
        markers+="${markers:+ }agents"
    fi
    d="$nyia_home/profiles/$name/prompts"
    if compgen -G "$d/*-overrides.md" >/dev/null 2>&1; then
        markers+="${markers:+ }prompts"
    fi
    [[ -n "$markers" ]] && echo "[$markers]"
    return 0
}

# Seed a persona's content dirs from a source ROOT (Plan 288b). Copies ONLY
# skills/agents/prompts using the propagation predicates (skill dir needs SKILL.md,
# agent is *.md, prompt is an activated *-overrides.md — never *.example), no-clobber.
# SECURITY (R11): NEVER copies config/ (the file-based API key lives at
# config/<assistant>.conf) or dotfiles — no credential crosses the profile boundary.
_profile_seed_from() {
    local src_root="$1" dest_root="$2"
    local sd af pf name
    if [[ -d "$src_root/skills" ]]; then
        mkdir -p "$dest_root/skills"
        for sd in "$src_root/skills"/*/; do
            [[ -d "$sd" ]] || continue
            [[ -f "$sd/SKILL.md" ]] || continue           # only real skills
            name="$(basename "$sd")"
            [[ -e "$dest_root/skills/$name" ]] && continue # no-clobber
            cp -r "$sd" "$dest_root/skills/$name"
        done
    fi
    if [[ -d "$src_root/agents" ]]; then
        mkdir -p "$dest_root/agents"
        for af in "$src_root/agents"/*.md; do
            [[ -f "$af" ]] || continue
            name="$(basename "$af")"
            [[ -e "$dest_root/agents/$name" ]] && continue
            cp "$af" "$dest_root/agents/$name"
        done
    fi
    if [[ -d "$src_root/prompts" ]]; then
        mkdir -p "$dest_root/prompts"
        for pf in "$src_root/prompts"/*-overrides.md; do
            [[ -f "$pf" ]] || continue                     # activated only, not .example
            name="$(basename "$pf")"
            [[ -e "$dest_root/prompts/$name" ]] && continue
            cp "$pf" "$dest_root/prompts/$name"
        done
    fi
}

# Create a profile (Plan 288b). Two modes:
#   plain            -> AUTH-ONLY account: registers the profile (so it lists) but
#                       scaffolds NO content dirs (auth-only inherits global content).
#   --persona [--from tech|non-tech|empty]
#                    -> PERSONA: scaffolds content dirs + prompt examples, writes the
#                       NYIA_PROFILE_MODE=persona marker, and seeds ONCE (copy-on-create):
#                       tech = your current global content, non-tech = the shipped
#                       template, empty (default) = no seed.
# Idempotent (no-clobber). Fail-closed on bad name / unknown --from / missing template.
_profile_handle_create() {
    local name="" persona=false from=""
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --persona)  persona=true; shift ;;
            --from)
                if [[ $# -lt 2 ]]; then
                    print_error "--from requires a value (tech, non-tech, or empty)"
                    exit 1
                fi
                from="$2"; shift 2 ;;
            --from=*)   from="${1#--from=}"; shift ;;
            -*)         print_error "Unknown option: $1"; exit 1 ;;
            *)
                if [[ -z "$name" ]]; then name="$1"; shift
                else print_error "Unexpected argument: $1"; exit 1; fi ;;
        esac
    done
    if [[ -z "$name" ]]; then
        print_error "Usage: nyia profile create <name> [--persona] [--from tech|non-tech|empty]"
        exit 1
    fi
    # Resolvers live in common-functions.sh, sourced by both dispatchers before this
    # file. Fail closed if unavailable rather than deriving paths independently.
    if ! declare -f resolve_profile_content_dir >/dev/null 2>&1 \
       || ! declare -f validate_profile_name >/dev/null 2>&1; then
        print_error "Profile resolver unavailable (common-functions.sh not loaded)"
        exit 1
    fi
    if [[ "$name" == "default" ]]; then
        print_error "'default' is the built-in profile — its content lives in the"
        print_error "global dirs (~/.config/nyiakeeper/{skills,agents,prompts})."
        exit 1
    fi
    if ! validate_profile_name "$name"; then
        print_error "Invalid profile name: '$name'"
        print_error "Use letters, digits, . _ - (no '..', '/', ':' or spaces)."
        exit 1
    fi
    # Validate --from (allowlist) BEFORE any filesystem action.
    if [[ -n "$from" ]]; then
        case "$from" in
            tech|non-tech|empty) ;;
            *) print_error "Unknown --from '$from' (use tech, non-tech, or empty)"; exit 1 ;;
        esac
        if [[ "$persona" != "true" ]]; then
            print_error "--from requires --persona (an auth-only profile inherits your global content)"
            exit 1
        fi
    fi
    # A persona with no --from seeds nothing (a full clone of your setup is surprising).
    [[ "$persona" == "true" && -z "$from" ]] && from="empty"

    local nyia_home profile_root existed=false
    nyia_home="$(get_nyiakeeper_home)"
    profile_root="$nyia_home/profiles/$name"
    [[ -d "$profile_root" ]] && existed=true

    # ---- AUTH-ONLY (plain create): register only, no content scaffold (R10) ----
    if [[ "$persona" != "true" ]]; then
        mkdir -p "$profile_root"
        if [[ -f "$profile_root/profile.conf" ]]; then
            echo "Profile '$name' already exists as a PERSONA (its own content)."
        elif [[ "$existed" == "true" ]]; then
            echo "Profile '$name' already exists (auth-only)."
        else
            echo "Created auth-only profile '$name'."
        fi
        echo ""
        echo "AUTH-ONLY: it uses its own account but INHERITS your global"
        echo "skills/agents/rules. Nyia base prompt, base skills, and team/project"
        echo "content are always present."
        echo ""
        echo "Attach an account:  nyia-<assistant> --profile $name --login"
        echo "Then use it:        nyia-<assistant> --profile $name"
        echo ""
        echo "Want its OWN isolated content instead? Re-run with:"
        echo "  nyia profile create $name --persona --from tech|non-tech|empty"
        return 0
    fi

    # ---- PERSONA: resolve the seed source FIRST so a missing template fails closed ----
    # (R7: no half-created persona when --from non-tech and the template is absent.)
    local seed_src=""
    case "$from" in
        tech)     seed_src="$nyia_home" ;;
        non-tech)
            if ! seed_src="$(resolve_profile_template_dir non-tech)"; then
                print_error "Cannot create persona '$name': the 'non-tech' template is not installed."
                print_error "Nothing was created. Use --from empty for a blank persona."
                exit 1
            fi ;;
        empty)    seed_src="" ;;
    esac

    # Warn if flipping an already-launched auth-only profile (stale auth-dir copies, R13).
    if [[ "$existed" == "true" && ! -f "$profile_root/profile.conf" ]]; then
        if compgen -G "$profile_root/*/skills" >/dev/null 2>&1 \
           || compgen -G "$profile_root/*/agents" >/dev/null 2>&1; then
            print_warning "Profile '$name' was used as auth-only; its session dirs may hold"
            print_warning "inherited global/team copies. For a clean persona, remove:"
            print_warning "  $profile_root/<assistant>/{skills,agents}"
        fi
    fi

    # Scaffold content dirs + prompt examples (persona only).
    local kind dir
    for kind in skills agents prompts; do
        if ! dir="$(resolve_profile_content_dir "$nyia_home" "$kind" "$name")"; then
            exit 1
        fi
        mkdir -p "$dir"
    done
    if declare -f ensure_prompts_directory >/dev/null 2>&1; then
        ensure_prompts_directory "$profile_root" >/dev/null 2>&1
    fi
    # Persona marker (idempotent, key-preserving — append if the file exists without the
    # key so any future keys in profile.conf are not clobbered by an overwrite).
    if [[ -f "$profile_root/profile.conf" ]]; then
        grep -qE '^NYIA_PROFILE_MODE=' "$profile_root/profile.conf" \
            || echo 'NYIA_PROFILE_MODE=persona' >> "$profile_root/profile.conf"
    else
        echo 'NYIA_PROFILE_MODE=persona' > "$profile_root/profile.conf"
    fi
    # Seed once (copy-on-create, no-clobber).
    [[ -n "$seed_src" ]] && _profile_seed_from "$seed_src" "$profile_root"

    if [[ "$existed" == "true" ]]; then
        echo "Updated persona '$name' (seeded --from $from):"
    else
        echo "Created persona '$name' (seeded --from $from):"
    fi
    local m
    m="$(_profile_content_markers "$nyia_home" "$name")"
    echo "  $profile_root/   content: ${m:-none yet}"
    echo "  ├── skills/    <- skill directories (each with SKILL.md)"
    echo "  ├── agents/    <- agent .md files"
    echo "  └── prompts/   <- base-overrides.md + <assistant>-overrides.md (see README)"
    echo ""
    echo "This is an ISOLATED persona: it uses ONLY its own content above (plus Nyia's"
    echo "base prompt, base skills, and team/project content). Edits here do NOT sync"
    echo "with your default — and later changes to your default do NOT flow in."
    echo ""
    echo "Attach an account:  nyia-<assistant> --profile $name --login"
    echo "Then use it:        nyia-<assistant> --profile $name"
}

# List profiles: always 'default', then each profiles/<name>/ directory.
# Marks the active profile (resolve_active_profile: --profile flag > global
# auth_profile config > default). Read-only — never creates anything.
_profile_handle_list() {
    local nyia_home
    nyia_home="$(get_nyiakeeper_home)"

    local active
    active="$(resolve_active_profile)"

    echo "Authentication profiles:"
    echo ""

    # Collect names: 'default' first, then directory entries under profiles/.
    local -a names=("default")
    local profiles_dir="$nyia_home/profiles"
    if [[ -d "$profiles_dir" ]]; then
        local entry name
        for entry in "$profiles_dir"/*/; do
            [[ -d "$entry" ]] || continue          # no-match glob guard
            name="$(basename "$entry")"
            # Skip an unlikely literal 'default' dir — it is shown above already.
            [[ "$name" == "default" ]] && continue
            names+=("$name")
        done
    fi

    local n marker mode content tag
    for n in "${names[@]}"; do
        if [[ "$n" == "$active" ]]; then
            marker="* "
        else
            marker="  "
        fi
        # Mode + content tags (Plan 288): named profiles only. The mode column is THE
        # distinction between two named profiles — auth-only inherits your global
        # content; a persona uses its OWN content (the markers below). The default
        # profile IS the global content, so it carries neither tag.
        tag=""
        if [[ "$n" != "default" ]]; then
            mode="$(resolve_profile_mode "$nyia_home" "$n" 2>/dev/null || echo auth)"
            if [[ "$mode" == "persona" ]]; then
                content="$(_profile_content_markers "$nyia_home" "$n")"
                tag="(persona)${content:+ $content}"
            else
                tag="(auth-only)"
            fi
        fi
        if [[ -n "$tag" ]]; then
            printf '  %s%-18s %s\n' "$marker" "$n" "$tag"
        else
            echo "  ${marker}${n}"
        fi
    done

    echo ""
    echo "Active: $active   (override per-command with --profile <name>)"
    echo "Named profiles are auth-only (inherit your global content) unless created"
    echo "with 'nyia profile create <name> --persona'."
}

# Shared dispatch entry for `nyia profile <subcommand>`.
handle_profile_command() {
    local subcommand="${1:-help}"
    shift || true
    case "$subcommand" in
        list|ls)
            _profile_handle_list "$@"
            ;;
        create)
            _profile_handle_create "$@"
            ;;
        help|--help|-h)
            _profile_show_help
            ;;
        *)
            print_error "Unknown profile command: $subcommand"
            _profile_show_help
            exit 1
            ;;
    esac
}
